name: .NET Core CI/CD

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: github4women

    - name: Build the application
      run: dotnet build --no-restore --configuration Release
      working-directory: github4women

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      working-directory: github4women

  custom-script-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Run a custom script
      run: |
        echo "Hello DotNET"
      